apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shares/volumes
    server: 192.168.22.1
