apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shares/pipeline
    server: 192.168.22.1
