apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpasswd-secret"}},"mappingMethod":"claim","name":"ocp-htpasswd","type":"HTPasswd"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-05-18T07:51:00Z"
  generation: 10
  name: cluster
  resourceVersion: "130165587"
  uid: 6e56c5d8-a64e-4bc9-b6c8-3e4d0a7b03d3
spec:
  identityProviders:
  - name: i3-users 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: i3-htpasswd
  - name: intern-users 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: intern-htpasswd
  - name: training-users
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: training-htpasswd